Vagrant.configure(2)  do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "graylog"

  config.vm.network :forwarded_port, guest: 80, host: 8090
  config.vm.network :forwarded_port, guest: 514, host: 514, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'udp'
  config.vm.network :forwarded_port, guest: 12201, host: 12201, protocol: 'tcp'

  config.vm.provider "virtualbox" do |v|
    v.memory = 4096
	v.cpus = 4
	v.name = "graylog2-server"
	v.gui = false
  end

  $script = <<SCRIPT
    cp /etc/apt/sources.list /home/vagrant/sources.list.backup
	sed -i s/archive.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list
	sed -i s/security.ubuntu.com/mirrors.aliyun.com/g /etc/apt/sources.list
    apt-get update
    echo 'Going to download Graylog...'
    curl -S -s -L -O https://packages.graylog2.org/releases/graylog-omnibus/ubuntu/graylog_latest.deb
    dpkg -i graylog_latest.deb
    graylog-ctl set-external-ip http://127.0.0.1:8090/api
	graylog-ctl set-timezone Asia/Shanghai
    graylog-ctl reconfigure
SCRIPT

  config.vm.provision "shell", inline: $script
end
